### ISSUE TITLE
Popular Music category should be corrected

### ISSUE THREAD

**Issue by harshapagilla** [Sunil02324/9by10-Tracker#4]
**Describe the bug**
When clicking on popular music category in the Music page, it is showing the page doesn't exist.

**To Reproduce**
1. Open the home page
2. Click on Database on the title bar of the page and select music 
3. Music Page will open showing the Popular music category on top of it.
4. Click on one of the songs in it.

**Expected behavior**
When we click on one of the songs it should redirect to the song page on the website.

**Screenshots**
![Screenshot (4)](https://user-images.githubusercontent.com/50137977/57062891-325d6880-6cdf-11e9-9111-f3f2847016a5.png)

**Applicable Devices & Versions:**
 All devices

**Comment by Sunil02324** [comment]
Bug Resolved!
